USE `essentialmode`;

CREATE TABLE `shops` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`store` varchar(100) NOT NULL,
	`item` varchar(100) NOT NULL,
	`price` int(11) NOT NULL,

	PRIMARY KEY (`id`)
);

INSERT INTO `shops` (store, item, price) VALUES
	('TwentyFourSeven','bread',5),
	('TwentyFourSeven','water',10),
	('RobsLiquor','bread',5),
	('RobsLiquor','water',10),
	('LTDgasoline','bread',5),
	('LTDgasoline','water',5),
	('TwentyFourSeven','pizza',5),
	('RobsLiquor','pizza',5),
	('LTDgasoline','pizza',5),
	('TwentyFourSeven','cocacola',5),
	('RobsLiquor','cocacola',5),
	('LTDgasoline','cocacola',5),
	('TwentyFourSeven','redbull',5),
	('RobsLiquor','redbull',5),
	('LTDgasoline','redbull',5),
	('TwentyFourSeven','hamburger',5),
	('RobsLiquor','hamburger',5),
	('LTDgasoline','hamburger',5),
	('TwentyFourSeven','taco',5),
	('RobsLiquor','taco',5),
	('LTDgasoline','taco',5),
	('TwentyFourSeven','bolchips',5),
	('RobsLiquor','bolchips',5),
	('LTDgasoline','bolchips',5),
	('TwentyFourSeven','donut',5),
	('RobsLiquor','donut',5),
	('LTDgasoline','donut',5),
	('TwentyFourSeven','frappucino',5),
	('RobsLiquor','frappucino',5),
	('LTDgasoline','frappucino',5),
	('TwentyFourSeven','twix',5),
	('RobsLiquor','twix',5),
	('LTDgasoline','twix',5),
	('TwentyFourSeven','cigarette',5),
	('RobsLiquor','cigarette',5),
	('LTDgasoline','cigarette',5),
	('TwentyFourSeven','croquettes',5),
	('RobsLiquor','croquettes',5),
	('LTDgasoline','croquettes',5),
	('Bar','duffbeer',50),
	('Bar','onepunchman',100),
	('Bar','dragonballcocktail',100),
	('Bar','yoshishooter',100),
	('ExtraItemsShop','boxpistol',10000),
	('ExtraItemsShop','boxsmg',15000),
	('ExtraItemsShop','boxshot',15000),
	('ExtraItemsShop','boxrifle',20000),
	('ExtraItemsShop','boxmg',20000),
	('ExtraItemsShop','boxsniper',30000),
	('ExtraItemsShop','boxflare',100),
	('ExtraItemsShop','bulletproof',10000),
	('ExtraItemsShop','firework',100),
	('ExtraItemsShop','grip',10000),
	('ExtraItemsShop','suppressor',10000),
	('Mcdonalds','qpc',5),
	('Mcdonalds','bigmac',5),
	('Mcdonalds','applepie',5),
	('Mcdonalds','sweettea',1),
	('Mcdonalds','fishfilet',5),
	('Mcdonalds','fries',5),
	('Utool','pickaxe',1000),
	('Utool','handcuffs',5000),
	('Utool','handcuffkey',10000),
	('Utool','binoculars',1000),
	('Utool','clothe',1000),
	('Utool','fixkit',1000),
	('Utool','lockpick',1000),
	('Utool','radio',1000),
	('Utool','shovel',1000),
	('Utool','diving_gear',1000),
	('Utool','nitro',1000),
	('WeedShop','highgradefemaleseed',1000),
	('WeedShop','lowgradefemaleseed',700),
	('WeedShop','highgrademaleseed',500),
	('WeedShop','lowgradefemaleseed',200),
	('WeedShop','highgradefert',500),
	('WeedShop','lowgradefert',200),
	('WeedShop','purifiedwater',500),
	('WeedShop','wateringcan',200),
	('WeedShop','plantpot',200),
	('WeedShop','dopebag',10),
	('WeedShop','drugscales',1000),
	('Pillbox','bandage',200),
	('Pillbox','medikit',1000),
	('Pillbox','defib',3000),
	('Pillbox','xanax',250);

