INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
 ('abra','Abra',-1,0,1),
 ('acetone','Acetone',-1,0,1),
 ('aerodactyl','Aerodactyl',-1,0,1),
 ('alakazam','Alakazam',-1,0,1),
 ('aluminum','Aluminum',-1,0,1),
 ('antifreeze','Antifreeze',-1,0,1),
 ('apple','Apple',-1,0,1),
 ('applejuice','Apple Juice',-1,0,1),
 ('applepie','Apple Pie',-1,0,1),
 ('arbok','Arbok',-1,0,1),
 ('arcanine','Arcanine',-1,0,1),
 ('articuno','Articuno',-1,0,1),
 ('bag','Train Bag',-1,0,1),
 ('bagofdope','Bag of Dope',-1,0,1),
 ('bandage','Bandage',-1,0,1),
 ('battery','Battery',-1,0,1),
 ('beedrill','Beedrill',-1,0,1),
 ('bellsprout','Bellsprout',-1,0,1),
 ('bigmac','Big Mac',-1,0,1),
 ('binoculars','Binoculars',-1,0,1),
 ('blacksmg','Black SMG',-1,0,1),
 ('black_card','Black Card',-1,0,1),
 ('blastoise','Blastoise',-1,0,1),
 ('blowpipe','Blowtorch',-1,0,1),
 ('boarmeat','Boar Meat',-1,0,1),
 ('boartusk','Boar Tusk',-1,0,1),
 ('bolchips','Lays',-1,0,1),
 ('book','Book',-1,0,1),
 ('boosterPack','Booster Pack',-1,0,1),
 ('boxflare','Ammo Box Flare',-1,0,1),
 ('boxmg','Ammo Box MG',-1,0,1),
 ('boxpistol','Ammo Box Pistol',-1,0,1),
 ('boxrifle','Ammo Box Rifle',-1,0,1),
 ('boxshot','Ammo Box Shotgun',-1,0,1),
 ('boxsmg','Ammo Box SMG',-1,0,1),
 ('boxsniper','Ammo Box Sniper',-1,0,1),
 ('brass','Brass',-1,0,1),
 ('bread','Bread',-1,0,1),
 ('brokenlaptop','Broken Laptop',-1,0,1),
 ('brokenphone','Broken Phone',-1,0,1),
 ('bulbasaur','Bulbasaur',-1,0,1),
 ('bulletcasing','Bullet Casing',-1,0,1),
 ('bulletproof','Bullet-Proof Vest',-1,0,1),
 ('butterfree','Butterfree',-1,0,1),
 ('cannabis','Cannabis',-1,0,1),
 ('carokit','Body Kit',-1,0,1),
 ('carotool','Tools',-1,0,1),
 ('casinochips','Chips',-1,0,1),
 ('caterpie','Caterpie',-1,0,1),
 ('chansey','Chansey',-1,0,1),
 ('charizard','Charizard',-1,0,1),
 ('charmander','Charmander',-1,0,1),
 ('charmeleon','Charmeleon',-1,0,1),
 ('cheese','Cheese',-1,0,1),
 ('chemicals','Chemicals',-1,0,1),
 ('chemicalslisence','Chemicals license',-1,0,1),
 ('chip','chip',-1,0,1),
 ('chips','chips',-1,0,1),
 ('cigarette','cigarette',-1,0,1),
 ('clam','Clams',-1,0,1),
 ('clefable','Clefable',-1,0,1),
 ('clefairy','Clefairy',-1,0,1),
 ('clothe','Cloth',-1,0,1),
 ('cloyster','Cloyster',-1,0,1),
 ('cocacola','CocaCola',-1,0,1),
 ('cocaine','Cocaine',-1,0,1),
 ('coca_leaf','Coca Leaf',-1,0,1),
 ('coke','Coke',-1,0,1),
 ('coke_pooch','box of coke',-1,0,1),
 ('compensator','Compensator',-1,0,1),
 ('copper','Copper',-1,0,1),
 ('coyotefur','Coyote Fur',-1,0,1),
 ('coyotemeat','Coyote Meat',-1,0,1),
 ('craftingtable','Crafting Table',-1,0,1),
 ('croquettes','Croquettes',-1,0,1),
 ('cubone','Cubone',-1,0,1),
 ('cutter','Saw',-1,0,1),
 ('darknet','Dark Net',-1,0,1),
 ('deermeat','Deer Meat',-1,0,1),
 ('deerskin','Deer Skin',-1,0,1),
 ('defib','Defib',-1,0,1),
 ('dewgong','Dewgong',-1,0,1),
 ('diamond','Diamond',-1,0,1),
 ('diamondring','Diamond Ring',-1,0,1),
 ('dia_box','Diamond Box',-1,0,1),
 ('diglett','Diglett',-1,0,1),
 ('ditto','Ditto',-1,0,1),
 ('diving_gear','Scuba Gear',-1,0,1),
 ('dj_tip','DJ Tips',-1,0,1),
 ('dodrio','Dodrio',-1,0,1),
 ('doduo','Doduo',-1,0,1),
 ('donut','Donut',-1,0,1),
 ('doors','Doors',-1,0,1),
 ('dopebag','Ziplock Bag',-1,0,1),
 ('dragonair','Dragonair',-1,0,1),
 ('dragonballcocktail','Dragon ball Cocktail',-1,0,1),
 ('dragonite','Dragonite',-1,0,1),
 ('dratini','Dratini',-1,0,1),
 ('drill','Drill',-1,0,1),
 ('drowzee','drowzee',-1,0,1),
 ('drugscales','Drug Scales',-1,0,1),
 ('duffbeer','Duff beer',-1,0,1),
 ('dugtrio','Dugtrio',-1,0,1),
 ('dvrcocktail','DVR cocktail',-1,0,1),
 ('eevee','Eevee',-1,0,1),
 ('ekans','Ekans',-1,0,1),
 ('electabuzz','Electabuzz',-1,0,1),
 ('electrode','Electrode',-1,0,1),
 ('emerald','Emerald',-1,0,1),
 ('engine','Engine',-1,0,1),
 ('essence','Gas',-1,0,1),
 ('exeggcute','Exeggcute',-1,0,1),
 ('exeggutor','Exeggutor',-1,0,1),
 ('extendedclip','Extended Clip',-1,0,1),
 ('fabric','Fabric',-1,0,1),
 ('fearow','Fearow',-1,0,1),
 ('finewood','Fine wood',-1,0,1),
 ('firework','Firework',-1,0,1),
 ('firstaidkit','First Aid Kit',-1,0,1),
 ('fish','Fish',-1,0,1),
 ('fishbait','Fish Bait',-1,0,1),
 ('fishfilet','Fish Filet',-1,0,1),
 ('fishingrod','Fishing Rod',-1,0,1),
 ('fixkit','Repair Kit',-1,0,1),
 ('fixtool','Repair Tools',-1,0,1),
 ('flareon','Flareon',-1,0,1),
 ('flashlightatt','flashlight Attachment',-1,0,1),
 ('flatscreen','Flat Screen TV',-1,0,1),
 ('frappucino','Frappe',-1,0,1),
 ('fries','Fries',-1,0,1),
 ('gastly','Gastly',-1,0,1),
 ('gazbottle','Gas Bottle',-1,0,1),
 ('gengar','Gengar',-1,0,1),
 ('geodude','Geodude',-1,0,1),
 ('glass','Glass',-1,0,1),
 ('gloom','Gloom',-1,0,1),
 ('golbat','Golbat',-1,0,1),
 ('gold','Gold',-1,0,1),
 ('goldbull','Gold Bullion',-1,0,1),
 ('goldeen','Goldeen',-1,0,1),
 ('golduck','Golduck',-1,0,1),
 ('goldwatch','Gold Watch',-1,0,1),
 ('gold_bar','Gold Bar',-1,0,1),
 ('golem','Golem',-1,0,1),
 ('graveler','Graveler',-1,0,1),
 ('grimer','Grimer',-1,0,1),
 ('grip','Grip',-1,0,1),
 ('growlithe','Growlithe',-1,0,1),
 ('gunpowder','Gun Powder',-1,0,1),
 ('gyarados','Gyarados',-1,0,1),
 ('gym_membership','Gym Membership',-1,0,1),
 ('hackerDevice','Hacking Device',-1,0,1),
 ('hacking_laptop','Hacking Laptop',-1,0,1),
 ('hamburger','Hamburger',-1,0,1),
 ('handcuffkey','Handcuff Keys',-1,0,1),
 ('handcuffs','Handcuffs',-1,0,1),
 ('haunter','Haunter',-1,0,1),
 ('headbag','Head Bag',-1,0,1),
 ('headlightb','Blue Headlights',-1,0,1),
 ('headlightbl','Black Light Headlights',-1,0,1),
 ('headlightg','Green Headlights',-1,0,1),
 ('headlightp','Pink Headlights',-1,0,1),
 ('headlightr','Red Headlights',-1,0,1),
 ('headlighty','Yellow Headlights',-1,0,1),
 ('heroin','Heroin',-1,0,1),
 ('hifi','Boombox',-1,0,1),
 ('highgradefemaleseed','Female Dope Seed+',-1,0,1),
 ('highgradefert','High-Grade Fertilizer',-1,0,1),
 ('highgrademaleseed','Male Dope Seed+',-1,0,1),
 ('hitmonchan','Hitmonchan',-1,0,1),
 ('hitmonlee','Hitmonlee',-1,0,1),
 ('holographic','Holographic Sight',-1,0,1),
 ('hood','Hood',-1,0,1),
 ('horsea','Horsea',-1,0,1),
 ('hulkcockail','Hulk Cockail',-1,0,1),
 ('humane_chemicalsH','Highly Radioactive Chemicals',-1,0,1),
 ('humane_chemicalsM','Radioactive Chemicals',-1,0,1),
 ('humane_chemicalsR','Humane Chemicals',-1,0,1),
 ('humane_lockpick','HL Lockpick',-1,0,1),
 ('humane_mask','Biohazard Mask',-1,0,1),
 ('humane_pliers','Pliers',-1,0,1),
 ('huntingbait','Hunting Bait',-1,0,1),
 ('huntingknife','Hunting Knife',-1,0,1),
 ('hydrochloric_acid','HydroChloric Acid',-1,0,1),
 ('hypno','Hypno',-1,0,1),
 ('id_card','ID Card',-1,0,1),
 ('id_card_f','Malicious Access Card',-1,3,1),
 ('ipad','iPad',-1,0,1),
 ('iphone','iPhone',-1,0,1),
 ('iron','Iron',-1,0,1),
 ('ivysaur','Ivysaur',-1,0,1),
 ('jewels','Jewels',-1,0,1),
 ('jigglypuff','Jigglypuff',-1,0,1),
 ('joint','Joint',-1,0,1),
 ('jolteon','Jolteon',-1,0,1),
 ('jynx','Jynx',-1,0,1),
 ('kabutops','Kabutops',-1,0,1),
 ('kadabra','Kadabra',-1,0,1),
 ('kakuna','Kakuna',-1,0,1),
 ('kangaskhan','kangaskhan',-1,0,1),
 ('kevlar','Kevlar',-1,0,1),
 ('keys_master_key','Master Key',-1,0,1),
 ('keys_master_key_single_use','Master Key (Single Use)',-1,0,1),
 ('keys_missionrow_pd_front','Mission Row PD Key (Front)',-1,0,1),
 ('kingler','Kingler',-1,0,1),
 ('knucklebalas','Knuckle Skin Ballas',-1,0,1),
 ('knucklediamond','Knuckle Skin Diamond',-1,0,1),
 ('knuckledollar','Knuckle Skin Dollar',-1,0,1),
 ('knucklehate','Knuckle Skin Hate',-1,0,1),
 ('knucklepimp','Knuckle Skin PIMP',-1,0,1),
 ('knucklepink','Knuckle Skin LOVE',-1,0,1),
 ('knuckleplayer','Knuckle Skin Player',-1,0,1),
 ('knucklevagos','Knuckle Skin Vagos',-1,0,1),
 ('koffing','Koffing',-1,0,1),
 ('krabby','Krabby',-1,0,1),
 ('lapras','Lapras',-1,0,1),
 ('laptop_h','Hacker Laptop',-1,0,1),
 ('largescope','Large Scope',-1,0,1),
 ('leather','Leather',-1,0,1),
 ('letter','Letter',-1,0,1),
 ('lettuce','Lettuce',-1,0,1),
 ('licenseplate','License Plate',-1,0,1),
 ('lickitung','Lickitung',-1,0,1),
 ('lockpick','Lock Pick',-1,0,1),
 ('lockpickv2','Lockpick (V2)',-1,0,1),
 ('lootchest','Loot Chest',-1,0,1),
 ('lowgradefemaleseed','Female Dope Seed',-1,0,1),
 ('lowgradefert','Low-Grade Fertilizer',-1,0,1),
 ('lowgrademaleseed','Male Dope Seed',-1,0,1),
 ('lsa','LSA',-1,0,1),
 ('lsd','LSD',-1,0,1),
 ('machamp','Machamp',-1,0,1),
 ('machoke','Machoke',-1,0,1),
 ('machop','Machop',-1,0,1),
 ('magikarp','Magikarp',-1,0,1),
 ('magmar','Magmar',-1,0,1),
 ('magnemite','Magnemite',-1,0,1),
 ('magneton','Magneton',-1,0,1),
 ('mankey','Mankey',-1,0,1),
 ('marijuana','Marijuana',-1,0,1),
 ('marowak','Marowak',-1,0,1),
 ('meat','Meat',-1,0,1),
 ('medikit','Medikit',-1,0,1),
 ('mediumscope','Medium Scope',-1,0,1),
 ('meowth','Meowth',-1,0,1),
 ('metalscrap','Scrap Metal',-1,0,1),
 ('metapod','Metapod',-1,0,1),
 ('meth','Meth',-1,0,1),
 ('meth_pooch','box of meth',-1,0,1),
 ('mew','Mew',-1,0,1),
 ('mewtwo','Mewtwo',-1,0,1),
 ('milkdragon','Milk dragon',-1,0,1),
 ('moltres','Moltres',-1,0,1),
 ('moneywash','MoneyWash License',-1,0,1),
 ('morphine','Morphine',-1,0,1),
 ('MountedScope','Scope Pistols MK2',-1,0,1),
 ('mr. mime','Mr. mime',-1,0,1),
 ('muffler','Muffler',-1,0,1),
 ('muk','Muk',-1,0,1),
 ('nidoking','Nidoking',-1,0,1),
 ('nidoqueen','Nidoqueen',-1,0,1),
 ('nidoran','Nidoran',-1,0,1),
 ('nidorina','Nidorina',-1,0,1),
 ('nightvision','Night Vision',-1,0,1),
 ('ninetales','Ninetales',-1,0,1),
 ('nitro','Nitro Bottle',-1,0,1),
 ('oddish','Oddish',-1,0,1),
 ('oilpump','Oil Pump',-1,0,1),
 ('omanyte','Omanyte',-1,0,1),
 ('omastar','Omastar',-1,0,1),
 ('onepunchman','One Punch Man Cocktail',-1,0,1),
 ('onix','Onix',-1,0,1),
 ('opal','Opal',-1,0,1),
 ('opium','Opium',-1,0,1),
 ('opium_pooch','box of opium',-1,0,1),
 ('oxygenmask','Oxygen Mask',-1,0,1),
 ('package','Package',-1,0,1),
 ('paintinge','Painting6',1,0,1),
 ('paintingf','Painting4',-1,0,1),
 ('paintingg','Painting5',-1,0,1),
 ('paintingh','Painting2',-1,0,1),
 ('paintingi','Painting1',-1,0,1),
 ('paintingj','Painting3',-1,0,1),
 ('paras','Paras',-1,0,1),
 ('parasect','Parasect',-1,0,1),
 ('pearl','Pearl',-1,0,1),
 ('persian','Persian',-1,0,1),
 ('petrol','Oil',-1,0,1),
 ('petrol_raffin','Processed oil',-1,0,1),
 ('phone','Phone',-1,0,1),
 ('pickaxe','Pickaxe',-1,0,1),
 ('pidgeotto','Pidgeotto',-1,0,1),
 ('pidgey','Pidgey',-1,0,1),
 ('pikachu','Pikachu',-1,0,1),
 ('pinsir','Pinsir',-1,0,1),
 ('pizza','Pizza',-1,0,1),
 ('plantpot','Plant Pot',-1,0,1),
 ('plastic','Plastic',-1,0,1),
 ('playersafe','Player Safe',-1,0,1),
 ('poliwag','Poliwag',-1,0,1),
 ('poliwhirl','Poliwhirl',-1,0,1),
 ('poliwrath','Poliwrath',-1,0,1),
 ('ponyta','Ponyta',-1,0,1),
 ('poppyresin','Poppy Resin',-1,0,1),
 ('porygon','Porygon',-1,0,1),
 ('potato','Potato',-1,0,1),
 ('powerade','Powerade',-1,0,1),
 ('primeape','Primeape',-1,0,1),
 ('protein_shake','Protein Shake',-1,0,1),
 ('psyduck','Psyduck',-1,0,1),
 ('purifiedwater','Purified Water',-1,0,1),
 ('qpc','QPC',-1,0,1),
 ('radio','Radio',-1,0,1),
 ('raichu','Raichu',-1,0,1),
 ('rapidash','Rapidash',-1,0,1),
 ('raticate','Raticate',-1,0,1),
 ('rattata','Rattata',-1,0,1),
 ('recipe_bagofdope','Recipe: Bag of Dope',-1,0,1),
 ('redbull','Redbull',-1,0,1),
 ('repairkit','Repair Kit',-1,0,1),
 ('rhydon','Rhydon',-1,0,1),
 ('rhyhorn','Rhyhorn',-1,0,1),
 ('rims','Rims',-1,0,1),
 ('rolex','Rolex',-1,0,1),
 ('rustycarparts','Rusty Car Parts',-1,0,1),
 ('rustymetal','Rusty Metal',-1,0,1),
 ('sandshrew','Sandshrew',-1,0,1),
 ('sandslash','Sandslash',-1,0,1),
 ('scope','Scope Rifles',-1,0,1),
 ('scrapmetal','Scrap Metal',-1,0,1),
 ('scratch_ticket','Scratching Ticket',-1,0,1),
 ('scyther','Scyther',-1,0,1),
 ('seadra','Seadra',-1,0,1),
 ('seaking','Seaking',-1,0,1),
 ('secure_card','Secure ID Card',-1,3,1),
 ('seel','Seel',-1,0,1),
 ('shark','Shark',-1,0,1),
 ('shellder','Shellder',-1,0,1),
 ('shovel','Shovel',-1,0,1),
 ('slowbro','Slowbro',-1,0,1),
 ('slowpoke','Slowpoke',-1,0,1),
 ('snorlax','Snorlax',-1,0,1),
 ('sodium_hydroxide','Sodium Hydroxide',-1,0,1),
 ('speakers','Speakers',-1,0,1),
 ('spearow','Spearow',-1,0,1),
 ('sportlunch','Sportlunch',-1,0,1),
 ('squirtle','Squirtle',-1,0,1),
 ('starmie','Starmie',-1,0,1),
 ('staryu','Staryu',-1,0,1),
 ('steel','Steel',-1,0,1),
 ('steelscraps','Steel Scrap',-1,0,1),
 ('steeringwheel','Steering Wheel',-1,0,1),
 ('stone','Stone',-1,0,1),
 ('subwoofer','Subwoofer',-1,0,1),
 ('sulfur','Sulfur',-1,0,1),
 ('sulfuric_acid','Sulfuric Acid',-1,0,1),
 ('suppressor','Suppressor',-1,0,1),
 ('sweettea','Sweet Tea',-1,0,1),
 ('taco','Taco',-1,0,1),
 ('tactitalmuzle','Tactical Muzzle Brake',-1,0,1),
 ('tangela','Tangela',-1,0,1),
 ('tauros','Tauros',-1,0,1),
 ('tentacool','Tentacool',-1,0,1),
 ('tentacruel','Tentacruel',-1,0,1),
 ('thermal_charge','Thermal Charge',-1,0,1),
 ('thermite','Thermite',-1,0,1),
 ('thionyl_chloride','Thionyl Chloride',-1,0,1),
 ('tirekit','Tire Kit',-1,0,1),
 ('titanium','Titanium',-1,0,1),
 ('togepi','Togepi',-1,0,1),
 ('tomato','Tomato',-1,0,1),
 ('train_gold','Train Gold',-1,0,1),
 ('treasurekey','Treasure Key',-1,0,1),
 ('trigger','Weapon Trigger',-1,0,1),
 ('trimmedweed','White Widow',-1,0,1),
 ('trunk','Trunk',-1,0,1),
 ('tunerchip','Tuner Chip',-1,0,1),
 ('tuning_laptop','Tuner Laptop',-1,0,1),
 ('turtle','Sea Turtle',-1,0,1),
 ('turtlebait','Turtle Bait',-1,0,1),
 ('twix','Twix',-1,0,1),
 ('vaporeon','Vaporeon',-1,0,1),
 ('vehgps','Vehicle GPS',-1,0,1),
 ('venomoth','Venomoth',-1,0,1),
 ('venonat','Venonat',-1,0,1),
 ('venusaur','Venusaur',-1,0,1),
 ('victreebel','Victreebel',-1,0,1),
 ('vileplume','Vileplume',-1,0,1),
 ('vipskin','VIP Skin Butterfly',-1,0,1),
 ('voltorb','Voltorb',-1,0,1),
 ('vulpix','Vulpix',-1,0,1),
 ('wallet','Wallet',-1,0,1),
 ('wartortle','Wartortle',-1,0,1),
 ('washed_stone','Washed stone',-1,0,1),
 ('water','Water',-1,0,1),
 ('wateringcan','Watering Can',-1,0,1),
 ('watermelon','Watermelon',-1,0,1),
 ('waterpump','Water Pump',-1,0,1),
 ('weakit','Weapon Kit',-1,0,1),
 ('weaponbarrel','Weapon Barrel',-1,0,1),
 ('weaponcase','Weapon Case',-1,0,1),
 ('weaponstock','Weapon Stock',-1,0,1),
 ('weedle','Weedle',-1,0,1),
 ('weepinbell','Weepinbell',-1,0,1),
 ('weezing','Weezing',-1,0,1),
 ('whiskey','Whiskey',-1,0,1),
 ('wigglytuff','Wigglytuff',-1,0,1),
 ('wood','Wood',-1,0,1),
 ('wool','Wool',-1,0,1),
 ('wpboomrf','Boom Rifles Skin',-1,0,1),
 ('wpgold','Gold Skin',-1,0,1),
 ('wpplat','Platinium Pistol 50 Skin',-1,0,1),
 ('wpskin','Weapon Skin',-1,0,1),
 ('wpskinrf','Wood Rifles Skin',-1,0,1),
 ('wpskullrf','Skull Rifles Skin',-1,0,1),
 ('wpwoodheavyp','Wood Heavy Pistol Skin',-1,0,1),
 ('wpzebrarf','Zebra Rifles Skin',-1,0,1),
 ('wrappedpumpshotgun','wrapped pumpshotgun',-1,0,1),
 ('xanax','Xanax',-1,0,1),
 ('yoshishooter','Yoshi shooter',-1,0,1),
 ('zapdos','Zapdos',-1,0,1),
 ('zubat','Zubat',-1,0,1);